Repository AgoraIO-Extensions/Agora-Flutter-SDK, pull requests merged in 2023-06, with the labels that each got.

#1082 feat: upgrade native sdk 4.1.0-build.2
  android/build.gradle
  example/lib/examples/basic/join_channel_video/join_channel_video.dart
  ios/agora_rtc_engine.podspec
  pubspec.yaml
  scripts/artifacts_version.sh
Labels: version:special

#1119 Littlegnal/special/native 4.1.1.6 build.3
  android/build.gradle
  ios/agora_rtc_engine.podspec
Labels: ci:ready_release_special

#1120 feat: upgrade native sdk 4.1.1.6-build.3
  pubspec.yaml
Labels: version:special, ci:ready_release_special

#1133 [ci] Allow external contributors to run the integration test
  .github/workflows/build.yml
  .github/workflows/rendering_test.yml
  .github/workflows/schedule-run-ci.yml
Labels: ci:schedule_run_ci

#1137 fix: no-op if call RtcEngine.release without calling RtcEngine.initialize directly
  lib/src/impl/agora_rtc_engine_impl.dart
  test_shard/integration_test_app/integration_test/testcases/rtcengine_smoke_test_testcases.dart
Labels: ci:schedule_run_ci

#1138 [ci][schedule-run-ci] Avoid trigger the ci run for internal contributors when action is labeled
  .github/workflows/schedule-run-ci.yml
Labels: ci:schedule_run_ci

#1140 [ci][schedule-run-ci]Fix ReferenceError: labeled is not defined
  .github/workflows/schedule-run-ci.yml
Labels: ci:schedule_run_ci

#1139 fix: do not setup native view if the widget is disposed in platform view rendering
  lib/src/impl/agora_video_view_impl.dart
  lib/src/impl/video_view_controller_impl.dart
  test_shard/integration_test_app/integration_test/testcases/agora_video_view_testcases.dart
Labels: ci:schedule_run_ci

#1141 [doc] daily update 2023-6-12
  lib/src/agora_base.dart
  lib/src/agora_log.dart
  lib/src/agora_media_base.dart
  lib/src/agora_media_engine.dart
  lib/src/agora_media_player.dart
  lib/src/agora_media_player_source.dart
  lib/src/agora_media_player_types.dart
  lib/src/agora_rtc_engine.dart
  lib/src/agora_rtc_engine_ex.dart
  lib/src/agora_rtc_engine_ext.dart
  lib/src/agora_spatial_audio.dart
  lib/src/audio_device_manager.dart
  lib/src/render/agora_video_view.dart
  lib/src/render/media_player_controller.dart
  lib/src/render/video_view_controller.dart
Labels: ci:doc, ci:schedule_run_ci

#1143 [ios][macos] Optimize dev experience
  example/ios/Podfile
  example/macos/Podfile
  ios/agora_rtc_engine.podspec
  macos/agora_rtc_engine.podspec
  test_shard/fake_test_app/ios/Podfile
  test_shard/fake_test_app/macos/Podfile
  test_shard/iris_tester/ios/IrisDebugger.podspec
  test_shard/iris_tester/ios/iris_tester.podspec
  test_shard/iris_tester/macos/IrisDebugger.podspec
  test_shard/iris_tester/macos/iris_tester.podspec
Labels: ci:schedule_run_ci

#1146 [ios] Run ios rendering test on github action runner
  .cirrus.yml
  .github/workflows/build.yml
Labels: ci:schedule_run_ci

#1149 Revert "[ios] Run ios rendering test on github action runner"
  .cirrus.yml
  .github/workflows/build.yml
Labels: ci:schedule_run_ci

#1157 [doc] daily update 2023-6-19
  lib/src/agora_rtc_engine.dart
  lib/src/audio_device_manager.dart
Labels: ci:doc, ci:schedule_run_ci

#1156 Reland "Revert "[ios] Run ios rendering test on github action runner""
  .cirrus.yml
  .github/workflows/build.yml
Labels: ci:schedule_run_ci

#1160 feat: upgrade native sdk dependencies 20230621
  android/build.gradle
  ios/agora_rtc_engine.podspec
  macos/agora_rtc_engine.podspec
  scripts/artifacts_version.sh
  windows/CMakeLists.txt
Labels: version:special, ci:skip

#1179 feat: release 6.1.1-sp.4116.b.3
  ci/rendering_test_ios.sh
  lib/src/impl/agora_video_view_impl.dart
  lib/src/impl/video_view_controller_impl.dart
  lib/src/render/video_view_controller.dart
  pubspec.yaml
  test_shard/integration_test_app/integration_test/testcases/fake_agora_video_view_testcases.dart
Labels: ci:ready_release_special
