Repository AgoraIO-Extensions/Agora-Flutter-SDK, pull requests merged in 2023-11, with the labels that each got.

#1417 feat: upgrade native sdk dependencies 20231101
  android/build.gradle
  ios/agora_rtc_engine.podspec
  macos/agora_rtc_engine.podspec
  scripts/artifacts_version.sh
  windows/CMakeLists.txt
Labels: version:special, ci:skip

#1406 feat: upgrade native sdk n423_w4182_0.3.0
  README.md
  example/lib/examples/basic/join_channel_audio/join_channel_audio.dart
  pubspec.yaml
Labels: version:special, ci:ready_release_special

#1419 Update version
  pubspec.yaml
Labels: version:special, ci:ready_release_special, ci:skip

#1415 feat: upgrade native sdk 4.2.3.1
  android/build.gradle
  ios/agora_rtc_engine.podspec
  lib/src/agora_base.dart
  lib/src/agora_base.g.dart
  lib/src/agora_media_base.dart
  lib/src/agora_media_base.g.dart
  lib/src/agora_media_player.dart
  lib/src/agora_media_player_types.dart
  lib/src/agora_media_player_types.g.dart
  lib/src/agora_rtc_engine.dart
  lib/src/agora_rtc_engine.g.dart
  lib/src/binding/agora_media_player_impl.dart
  lib/src/binding/agora_rtc_engine_event_impl.dart
  lib/src/binding/agora_rtc_engine_impl.dart
  lib/src/binding/call_api_event_handler_buffer_ext.dart
  lib/src/binding/event_handler_param_json.dart
  lib/src/binding/event_handler_param_json.g.dart
  lib/src/impl/agora_rtc_engine_impl.dart
  lib/src/impl/audio_device_manager_impl.dart
  lib/src/impl/media_player_controller_impl.dart
  macos/agora_rtc_engine.podspec
  pubspec.yaml
  scripts/artifacts_version.sh
  scripts/code_gen.sh
  test_shard/fake_test_app/integration_test/generated/mediaengine_audioframeobserver_testcases.generated.dart
  test_shard/fake_test_app/integration_test/generated/mediaengine_fake_test.generated.dart
  test_shard/fake_test_app/integration_test/generated/mediaplayer_fake_test.generated.dart
  test_shard/fake_test_app/integration_test/generated/rtcengine_fake_test.generated.dart
  test_shard/fake_test_app/integration_test/generated/rtcengine_rtcengineeventhandler_testcases.generated.dart
  test_shard/fake_test_app/integration_test/testcases/rtcengine_rtcengineeventhandler_testcases.dart
  tool/terra/terra_config_main.yaml
  tool/testcase_gen/bin/event_handler_gen_config.dart
  windows/CMakeLists.txt
Labels: version:special, ci:ready_release_special

#1429 Update the web integration section in README.md
  README.md
Labels: ci:skip

#1426 [fix] [android] Use SurfaceView instead of TextureView
  android/src/main/java/io/agora/agora_rtc_ng/AgoraPlatformViewFactory.java
Labels: ci:schedule_run_ci

#1436 feat: upgrade native sdk dependencies 20231114
  android/build.gradle
  ios/agora_rtc_engine.podspec
  macos/agora_rtc_engine.podspec
  scripts/artifacts_version.sh
  windows/CMakeLists.txt
Labels: version:special, ci:skip

#1439 feat: upgrade native sdk dependencies 20231116
  android/build.gradle
  android/src/main/cpp/third_party/include/agora_rtc/AgoraBase.h
  android/src/main/cpp/third_party/include/agora_rtc/AgoraMediaBase.h
  android/src/main/cpp/third_party/include/agora_rtc/AgoraMediaPlayerTypes.h
  android/src/main/cpp/third_party/include/agora_rtc/IAgoraH265Transcoder.h
  android/src/main/cpp/third_party/include/agora_rtc/IAgoraMediaPlayer.h
  android/src/main/cpp/third_party/include/agora_rtc/IAgoraMediaPlayerSource.h
  android/src/main/cpp/third_party/include/agora_rtc/IAgoraMusicContentCenter.h
  android/src/main/cpp/third_party/include/agora_rtc/IAgoraRtcEngine.h
  android/src/main/cpp/third_party/include/agora_rtc/IAgoraRtcEngineEx.h
  android/src/main/cpp/third_party/include/agora_rtc/IAgoraRtmClient.h
  android/src/main/cpp/third_party/include/agora_rtc/IAgoraStreamChannel.h
  android/src/main/cpp/third_party/include/agora_rtc/IAudioDeviceManager.h
  android/src/main/cpp/third_party/include/iris/iris_base.h
  android/src/main/cpp/third_party/include/iris/iris_rtc_api_type.h
  android/src/main/cpp/third_party/include/iris/iris_rtc_high_performance_c_api.h
  ios/agora_rtc_engine.podspec
  macos/agora_rtc_engine.podspec
  scripts/artifacts_version.sh
  windows/CMakeLists.txt
Labels: version:special, ci:skip

#1440 feat: upgrade native sdk dependencies 20231116
  android/build.gradle
  ios/agora_rtc_engine.podspec
  macos/agora_rtc_engine.podspec
  scripts/artifacts_version.sh
  windows/CMakeLists.txt
Labels: version:special, ci:skip

#1438 feat: upgrade native sdk 4.2.3.2
  .github/workflows/build.yml
  android/build.gradle
  android/src/main/cpp/third_party/include/agora_rtc/AgoraBase.h
  android/src/main/cpp/third_party/include/agora_rtc/AgoraMediaBase.h
  android/src/main/cpp/third_party/include/agora_rtc/AgoraMediaPlayerTypes.h
  android/src/main/cpp/third_party/include/agora_rtc/IAgoraH265Transcoder.h
  android/src/main/cpp/third_party/include/agora_rtc/IAgoraMediaPlayer.h
  android/src/main/cpp/third_party/include/agora_rtc/IAgoraMediaPlayerSource.h
  android/src/main/cpp/third_party/include/agora_rtc/IAgoraMusicContentCenter.h
  android/src/main/cpp/third_party/include/agora_rtc/IAgoraRtcEngine.h
  android/src/main/cpp/third_party/include/agora_rtc/IAgoraRtcEngineEx.h
  android/src/main/cpp/third_party/include/agora_rtc/IAgoraRtmClient.h
  android/src/main/cpp/third_party/include/agora_rtc/IAgoraStreamChannel.h
  android/src/main/cpp/third_party/include/agora_rtc/IAudioDeviceManager.h
  android/src/main/cpp/third_party/include/iris/iris_base.h
  android/src/main/cpp/third_party/include/iris/iris_rtc_api_type.h
  android/src/main/cpp/third_party/include/iris/iris_rtc_high_performance_c_api.h
  ios/agora_rtc_engine.podspec
  macos/agora_rtc_engine.podspec
  pubspec.yaml
  scripts/artifacts_version.sh
  windows/CMakeLists.txt
Labels: version:special, ci:ready_release_special

#1448 [doc] daily update 2023-11-23
  lib/src/agora_base.dart
  lib/src/agora_log.dart
  lib/src/agora_media_base.dart
  lib/src/agora_media_engine.dart
  lib/src/agora_media_player.dart
  lib/src/agora_rtc_engine.dart
  lib/src/agora_rtc_engine_ex.dart
Labels: ci:doc

#1450 feat: upgrade native sdk 4.1.1.21.a
  android/build.gradle
  ios/agora_rtc_engine.podspec
  pubspec.yaml
Labels: version:special, ci:ready_release_special

#1449 feat: upgrade native sdk 4.2.6.1
  macos/agora_rtc_engine.podspec
  pubspec.yaml
  scripts/artifacts_version.sh
  windows/CMakeLists.txt
Labels: version:special, ci:ready_release_special

#1453 feat: upgrade native sdk 4.2.6.1
  android/build.gradle
  ios/agora_rtc_engine.podspec
  pubspec.yaml
Labels: version:special, ci:ready_release_special

#1455 feat: upgrade native sdk 4.1.1.21
  pubspec.yaml
Labels: version:special, ci:ready_release_special
