Repository AgoraIO-Extensions/Agora-Flutter-SDK, pull requests merged in 2023-07, with the labels that each got.

#1189 feat: upgrade native sdk dependencies 20230704
  android/build.gradle
  ios/agora_rtc_engine.podspec
  macos/agora_rtc_engine.podspec
  scripts/artifacts_version.sh
  windows/CMakeLists.txt
Labels: version:special, ci:skip

#1205 fix: Add missing `NetworkType.networkTypeMobile5g`
  lib/src/agora_base.dart
  lib/src/agora_base.g.dart
  lib/src/binding/event_handler_param_json.g.dart
Labels: ci:schedule_run_ci

#1230 [AUTO] Update doc 422
  lib/src/agora_base.dart
  lib/src/agora_log.dart
  lib/src/agora_media_base.dart
  lib/src/agora_media_engine.dart
  lib/src/agora_media_player.dart
  lib/src/agora_media_player_source.dart
  lib/src/agora_media_player_types.dart
  lib/src/agora_rtc_engine.dart
  lib/src/agora_rtc_engine_ex.dart
  lib/src/agora_spatial_audio.dart
  lib/src/audio_device_manager.dart
  lib/src/impl/agora_video_view_impl.dart
  lib/src/render/agora_video_view.dart
  lib/src/render/media_player_controller.dart
  lib/src/render/video_view_controller.dart
Labels: ci:doc

#1241 [ios] Tmp fix CFBundleShortVersionString/CFBundleVersion issue for iris_event
  example/pubspec.lock
  pubspec.yaml
Labels: ci:ready_release_special
