Repository AgoraIO-Extensions/Agora-Flutter-SDK, pull requests merged in 2024-12, with the labels that each got.

#2120 feat: upgrade native sdk dependencies 20241203
  android/build.gradle
  internal/deps_summary.txt
  ios/agora_rtc_engine.podspec
  macos/agora_rtc_engine.podspec
  scripts/artifacts_version.sh
  windows/CMakeLists.txt
Labels: version:special, ci:skip

#2121 feat: upgrade native sdk dependencies 20241203
  README.md
  example/web/index.html
  scripts/iris_web_version.js
Labels: version:special, ci:skip

#2122 feat: upgrade native sdk dependencies 20241203
  README.md
  example/web/index.html
  scripts/iris_web_version.js
Labels: version:special, ci:skip

#2123 [AUTO] Update doc
  lib/src/agora_base.dart
  lib/src/agora_media_base.dart
  lib/src/agora_media_player.dart
  lib/src/agora_media_player_source.dart
  lib/src/agora_media_player_types.dart
  lib/src/agora_rtc_engine.dart
  lib/src/agora_rtc_engine_ex.dart
  lib/src/audio_device_manager.dart
Labels: ci:doc

#2136 feat: upgrade native sdk to 4.3.2.11
  android/build.gradle
  android/src/main/cpp/third_party/include/agora_rtc/AgoraBase.h
  android/src/main/cpp/third_party/include/agora_rtc/AgoraMediaBase.h
  android/src/main/cpp/third_party/include/agora_rtc/IAgoraRtcEngine.h
  android/src/main/cpp/third_party/include/agora_rtc/IAgoraRtcEngineEx.h
  example/lib/examples/advanced/picture_in_picture/picture_in_picture.dart
  internal/deps_summary.txt
  ios/agora_rtc_engine.podspec
  lib/src/agora_base.dart
  lib/src/agora_base.g.dart
  lib/src/agora_media_base.dart
  lib/src/agora_media_base.g.dart
  lib/src/agora_media_engine.dart
  lib/src/agora_media_player.dart
  lib/src/agora_media_player_source.dart
  lib/src/agora_media_player_types.dart
  lib/src/agora_rtc_engine.dart
  lib/src/agora_rtc_engine.g.dart
  lib/src/agora_rtc_engine_ex.dart
  lib/src/audio_device_manager.dart
  lib/src/binding/agora_rtc_engine_ex_impl.dart
  lib/src/binding/call_api_event_handler_buffer_ext.dart
  lib/src/binding/event_handler_param_json.g.dart
  lib/src/impl/platform/io/global_video_view_controller_platform_io.dart
  lib/src/impl/video_view_controller_impl.dart
  lib/src/render/video_view_controller.dart
  macos/agora_rtc_engine.podspec
  pubspec.yaml
  scripts/artifacts_version.sh
  test_shard/fake_test_app/integration_test/generated/rtcengine_rtcengineeventhandler_testcases.generated.dart
  test_shard/fake_test_app/integration_test/generated/rtcengineex_fake_test.generated.dart
  tool/terra/package.json
  tool/terra/terra_config_main.yaml
  tool/testcase_gen/bin/event_handler_gen_config.dart
  tool/testcase_gen/lib/rtc_engine_event_handler_somke_test_generator.dart
  windows/CMakeLists.txt
Labels: ci:schedule_build_example, ci:building_example, ci:ready_release_special

#2152 feat: upgrade native audio sdk 4.4.0
  android/build.gradle
  internal/deps_summary.txt
  ios/agora_rtc_engine.podspec
  pubspec.yaml
  scripts/artifacts_version.sh
Labels: version:special, ci:ready_release_special

#2150 [ci] Fix CI failed caused by using an unsupported NodeJS version (#2070)
  .github/workflows/prepare-release.yml
  .github/workflows/release.yml
  .github/workflows/release_special_version.yml
Labels: ci:skip

#2157 chore: fixed max flutter version with 3.24.5 when do integration test
  .github/workflows/build.yml
Labels: ci:skip

#2158 chore: upgrade native sdk to 4.3.2.235 audio only
  android/build.gradle
  ios/agora_rtc_engine.podspec
  pubspec.yaml
Labels: ci:ready_release_special, ci:skip

#2160 feat: upgrade native sdk 4.3.2.234
  android/build.gradle
  android/src/main/cpp/third_party/include/agora_rtc/AgoraBase.h
  android/src/main/cpp/third_party/include/agora_rtc/IAgoraRtcEngine.h
  android/src/main/cpp/third_party/include/agora_rtc/IAgoraRtcEngineEx.h
  example/lib/examples/advanced/index.dart
  example/lib/examples/advanced/picture_in_picture/picture_in_picture.dart
  example/lib/examples/advanced/stream_rdt_message/stream_rdt_message.dart
  internal/deps_summary.txt
  ios/agora_rtc_engine.podspec
  lib/src/agora_base.dart
  lib/src/agora_base.g.dart
  lib/src/agora_rtc_engine.dart
  lib/src/agora_rtc_engine_ex.dart
  lib/src/binding/agora_rtc_engine_event_impl.dart
  lib/src/binding/agora_rtc_engine_ex_impl.dart
  lib/src/binding/agora_rtc_engine_impl.dart
  lib/src/binding/event_handler_param_json.dart
  lib/src/binding/event_handler_param_json.g.dart
  pubspec.yaml
  scripts/artifacts_version.sh
  test_shard/fake_test_app/integration_test/generated/event_ids_mapping_gen.dart
  test_shard/fake_test_app/integration_test/generated/rtcengine_fake_test.generated.dart
  test_shard/fake_test_app/integration_test/generated/rtcengine_rtcengineeventhandler_testcases.generated.dart
  test_shard/fake_test_app/integration_test/generated/rtcengineex_fake_test.generated.dart
  tool/terra/configs/cud_node_parser.config.ts
  tool/terra/terra_config_main.yaml
Labels: ci:ready_release_special

#2167 fix: optimize pip
  example/lib/examples/advanced/index.dart
  example/lib/examples/advanced/picture_in_picture/picture_in_picture.dart
  example/lib/examples/advanced/picture_in_picture/picture_in_picture_android.dart
  example/lib/examples/advanced/picture_in_picture/picture_in_picture_ios.dart
  lib/src/impl/video_view_controller_impl.dart
  lib/src/render/video_view_controller.dart
  pubspec.yaml
Labels: ci:ready_release_special

#2171 feat: upgrade native sdk 4.2.6.20
  .github/workflows/build.yml
  android/build.gradle
  android/src/main/cpp/third_party/include/agora_rtc/IAgoraRtcEngine.h
  android/src/main/cpp/third_party/include/agora_rtc/IAgoraRtcEngineEx.h
  android/src/main/cpp/third_party/include/iris/iris_rtc_api_type.h
  example/lib/main.dart
  internal/deps_summary.txt
  ios/agora_rtc_engine.podspec
  lib/src/agora_base.dart
  lib/src/agora_base.g.dart
  lib/src/agora_media_base.dart
  lib/src/agora_media_engine.dart
  lib/src/agora_media_player.dart
  lib/src/agora_media_player_source.dart
  lib/src/agora_media_player_types.dart
  lib/src/agora_rtc_engine.dart
  lib/src/agora_rtc_engine_ex.dart
  lib/src/audio_device_manager.dart
  lib/src/binding/agora_media_engine_impl.dart
  lib/src/binding/agora_rtc_engine_event_impl.dart
  lib/src/binding/agora_rtc_engine_ex_impl.dart
  lib/src/binding/agora_rtc_engine_impl.dart
  lib/src/binding/event_handler_param_json.dart
  lib/src/binding/event_handler_param_json.g.dart
  macos/agora_rtc_engine.podspec
  pubspec.yaml
  scripts/artifacts_version.sh
  test_shard/fake_test_app/integration_test/generated/event_ids_mapping_gen.dart
  test_shard/fake_test_app/integration_test/generated/mediaengine_fake_test.generated.dart
  test_shard/fake_test_app/integration_test/generated/rtcengine_fake_test.generated.dart
  test_shard/fake_test_app/integration_test/generated/rtcengine_rtcengineeventhandler_testcases.generated.dart
  test_shard/fake_test_app/integration_test/generated/rtcengineex_fake_test.generated.dart
  test_shard/fake_test_app/lib/main.dart
  test_shard/integration_test_app/integration_test/fake/fake_iris_method_channel.dart
  test_shard/integration_test_app/integration_test/testcases/fake_agora_video_view_testcases.dart
  test_shard/integration_test_app/lib/fake_remote_user_main.dart
  test_shard/integration_test_app/lib/main.dart
  test_shard/rendering_test/lib/main.dart
  tool/terra/terra_config_main.yaml
  windows/CMakeLists.txt
Labels: ci:ready_release_special
