Repository AgoraIO-Extensions/Agora-Flutter-SDK, pull requests merged in 2024-03, with the labels that each got.

#1607 [doc] daily update 2024-3-5
  lib/src/agora_base.dart
  lib/src/agora_media_engine.dart
  lib/src/agora_media_player.dart
  lib/src/agora_rtc_engine.dart
  lib/src/agora_rtc_engine_ex.dart
Labels: ci:doc

#1616 feat: upgrade native sdk 4.2.6.4-build.2
  example/lib/examples/advanced/process_video_raw_data/process_video_raw_data.dart
  example/pubspec.yaml
  ios/agora_rtc_engine.podspec
  pubspec.yaml
Labels: version:special, ci:ready_release_special

#1619 feat: upgrade native sdk dependencies 20240313
  android/build.gradle
  android/src/main/cpp/third_party/include/agora_rtc/AgoraBase.h
  android/src/main/cpp/third_party/include/agora_rtc/IAgoraRtcEngine.h
  ios/agora_rtc_engine.podspec
  macos/agora_rtc_engine.podspec
  scripts/artifacts_version.sh
  windows/CMakeLists.txt
Labels: version:special, ci:skip

#1623 [ci] Add code-gen.yaml
  .github/workflows/code-gen.yaml
Labels: ci:skip

#1625 [ci][code-gen.yaml] Fix run failed
  .github/workflows/code-gen.yaml
Labels: ci:skip

#1631 feat: upgrade native sdk dependencies 20240318
  android/build.gradle
  ios/agora_rtc_engine.podspec
  macos/agora_rtc_engine.podspec
  scripts/artifacts_version.sh
  windows/CMakeLists.txt
Labels: version:special, ci:skip

#1643 feat: upgrade native sdk dependencies 20240322
  scripts/artifacts_version.sh
  windows/CMakeLists.txt
Labels: version:special, ci:skip

#1642 feat: upgrade native sdk dependencies 20240322
  android/build.gradle
  android/src/main/cpp/third_party/include/agora_rtc/AgoraBase.h
  android/src/main/cpp/third_party/include/agora_rtc/AgoraMediaBase.h
  android/src/main/cpp/third_party/include/agora_rtc/IAgoraRtcEngine.h
  ios/agora_rtc_engine.podspec
  macos/agora_rtc_engine.podspec
  scripts/artifacts_version.sh
  windows/CMakeLists.txt
Labels: version:special, ci:skip

#1644 feat: upgrade native sdk dependencies 20240322
  android/build.gradle
  ios/agora_rtc_engine.podspec
  macos/agora_rtc_engine.podspec
  scripts/artifacts_version.sh
  windows/CMakeLists.txt
Labels: version:special, ci:skip

#1650 Improve github issue bug report template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/workflows/more-detail-wanted.yaml
Labels: ci:skip

#1654 feat: upgrade native sdk dependencies 20240326
  android/build.gradle
  ios/agora_rtc_engine.podspec
  macos/agora_rtc_engine.podspec
  scripts/artifacts_version.sh
  windows/CMakeLists.txt
Labels: version:special, ci:skip

#1658 Allow newer `flutter_lints` versions
  pubspec.yaml
Labels: external:contribution, ci:schedule_run_ci

#1662 feat: upgrade native sdk 4.3.0.1
  android/build.gradle
  ios/agora_rtc_engine.podspec
  pubspec.yaml
Labels: version:special, ci:ready_release_special
