Repository AgoraIO-Extensions/Agora-Flutter-SDK, pull requests merged in 2025-03, with the labels that each got.

#2212 chore: release 6.3.2-sp.43211.b.5
  pubspec.yaml
Labels: ci:ready_release_special, ci:skip

#2186 chore: add sync scripts for atlas
  .github/workflows/run_sync.yml
  scripts/change_publisher.sh
Labels: ci:skip

#2213 feat: upgrade native sdk 4.3.2.236
  android/build.gradle
  internal/deps_summary.txt
  ios/agora_rtc_engine.podspec
  pubspec.yaml
  scripts/artifacts_version.sh
Labels: version:special, ci:ready_release_special

#2218 chore: do not exit with 1 when there is not crash files
  .github/workflows/build.yml
Labels: ci:skip

#2225 chore: add empty workflow files (#2198)
  .github/workflows/on_pr_external.yml
  .github/workflows/on_pr_internal.yml
  .github/workflows/run_build_example.yml
  .github/workflows/run_code_gen.yml
  .github/workflows/run_pub.yml
  .github/workflows/run_sync.yml
  .github/workflows/run_test.yml
  .github/workflows/run_update_deps.yml
Labels: ci:skip

#2226 chore: new workflow to build example (#2199)
  .github/workflows/on_pr_external.yml
  .github/workflows/on_pr_internal.yml
  .github/workflows/run_build_example.yml
  .github/workflows/run_code_gen.yml
  .github/workflows/run_pub.yml
  .github/workflows/run_sync.yml
  .github/workflows/run_test.yml
  .github/workflows/run_update_deps.yml
  example/ios/export.plist
Labels: ci:skip

#2233 chore: add sync scripts for atlas (#2186)
  .github/workflows/run_sync.yml
  scripts/change_publisher.sh
Labels: ci:skip

#2223 ⚡️ Make data classes serializable
  lib/src/_serializable.dart
  lib/src/agora_base.dart
  lib/src/agora_log.dart
  lib/src/agora_media_base.dart
  lib/src/agora_media_player_types.dart
  lib/src/agora_media_streaming_source.dart
  lib/src/agora_music_content_center.dart
  lib/src/agora_rhythm_player.dart
  lib/src/agora_rtc_engine.dart
  lib/src/agora_rtc_engine_ex.dart
  lib/src/agora_spatial_audio.dart
  lib/src/binding/call_api_impl_params_json.dart
  lib/src/binding/event_handler_param_json.dart
  lib/src/impl/agora_music_content_center_impl_json.dart
  lib/src/impl/json_converters.dart
Labels: ci:schedule_run_ci

#2246 chore: upgrade sdk
  internal/deps_summary.txt
  pubspec.yaml
  scripts/artifacts_version.sh
  windows/CMakeLists.txt
Labels: ci:ready_release_special, ci:skip

#2249 chore: do not run schedule: stale issues every half an hour but every…
  .github/workflows/schedule_stale_issues.yml
Labels: ci:skip

#2252 chore: modify comment of job triage-to-agora-support (#2251)
  .github/workflows/on_issue_labeled.yml
Labels: ci:skip
