Repository AgoraIO-Extensions/Agora-Flutter-SDK, pull requests merged in 2025-04, with the labels that each got.

#2259 fix #2258: remove unused codes
  android/src/main/java/io/agora/agora_rtc_ng/AgoraRtcNgPlugin.java
  lib/src/impl/agora_rtc_engine_impl.dart
  pubspec.yaml
Labels: bug

#2263 chore: support to publish rc version to pub
  .github/actions/pub/Dockerfile
  .github/actions/pub/action.yml
  .github/actions/pub/entrypoint.sh
  .github/workflows/on_pr_closed.yml
  .github/workflows/run_pub.yml
Labels: ci:skip

#2266 chore: upgrade sdk
  internal/deps_summary.txt
  pubspec.yaml
  scripts/artifacts_version.sh
  windows/CMakeLists.txt
Labels: ci:ready_release_special

#2267 chore: upgrade sdk to build.4
  internal/deps_summary.txt
  pubspec.yaml
  scripts/artifacts_version.sh
  windows/CMakeLists.txt
Labels: ci:schedule_build_example, ci:building_example, ci:ready_release_special

#2273 fix: Undefined name 'platformViewRegistry'.
  lib/src/impl/platform/web/global_video_view_controller_platform_web.dart
Labels: ci:schedule_run_ci

#2284 chore: upgrade sdk to 4.2.6.160
  internal/deps_summary.txt
  pubspec.yaml
  scripts/artifacts_version.sh
  windows/CMakeLists.txt
Labels: ci:ready_release_special
