Repository AgoraIO-Extensions/Agora-Flutter-SDK, pull requests merged in 2025-02, with the labels that each got.

#2195 feat: upgrade native sdk 4.5.0
  android/build.gradle
  internal/deps_summary.txt
  ios/agora_rtc_engine.podspec
  pubspec.yaml
  scripts/artifacts_version.sh
Labels: version:special, ci:ready_release_special

#2198 chore: add empty workflow files
  .github/workflows/on_pr_external.yml
  .github/workflows/on_pr_internal.yml
  .github/workflows/run_build_example.yml
  .github/workflows/run_code_gen.yml
  .github/workflows/run_pub.yml
  .github/workflows/run_sync.yml
  .github/workflows/run_test.yml
  .github/workflows/run_update_deps.yml
Labels: ci:skip

#2197 feat: upgrade native sdk 4.5.0.2 for iOS and Android
  android/build.gradle
  internal/deps_summary.txt
  ios/agora_rtc_engine.podspec
  pubspec.yaml
  scripts/artifacts_version.sh
Labels: ci:ready_release_special, ci:schedule_run_ci

#2201 feat: prepare to release 6.3.2-sp.43211.b.4
  pubspec.yaml
Labels: ci:ready_release_special

#2203 chore: new workflow to update deps
  .github/actions/gen_code/action.yml
  .github/actions/prepare_branch/action.yml
  .github/workflows/build.yml
  .github/workflows/code-gen.yaml
  .github/workflows/integration-test-iris-artifacts.yml
  .github/workflows/on_pr_external.yml
  .github/workflows/on_pr_internal.yml
  .github/workflows/run_build_example.yml
  .github/workflows/run_code_gen.yml
  .github/workflows/run_gen_code.yml
  .github/workflows/run_pub.yml
  .github/workflows/run_sync.yml
  .github/workflows/run_test.yml
  .github/workflows/run_update_deps.yml
  .github/workflows/schedule-run-ci-external.yml
  .github/workflows/schedule-run-ci-internal.yml
  android/build.gradle
  ci/run_android_test.sh
  ci/run_flutter_integration_test.sh
  ci/run_flutter_integration_test_android.sh
  ci/run_flutter_integration_test_ios.sh
  ci/run_flutter_integration_test_web.sh
  ci/run_flutter_macos_integration_test.sh
  ci/run_flutter_windows_integration_test.sh
  ci/run_ios_test.sh
  ci/run_update_deps.sh
  internal/deps_summary.txt
  ios/agora_rtc_engine.podspec
  lib/src/agora_rtc_engine.dart
  macos/agora_rtc_engine.podspec
  scripts/artifacts_version.sh
  scripts/build-android-arch.sh
  scripts/build-android.sh
  scripts/build-internal-testing-macos.sh
  scripts/build-internal-testing.sh
  scripts/build-ios-arch.sh
  scripts/build-iris-all.sh
  scripts/build-iris-android.sh
  scripts/build-iris-ios.sh
  scripts/build-iris-macos-arch.sh
  scripts/build-iris-macos.sh
  scripts/build-iris-web.sh
  scripts/build-iris-windows.sh
  scripts/build-mac.sh
  scripts/code_gen.sh
  scripts/download_unzip_iris_cdn_artifacts.sh
  test_shard/integration_test_app/pubspec.yaml
  tool/terra/terra_config_main.yaml
  tool/testcase_gen/build.sh
  tool/testcase_gen/pubspec.yaml
  windows/CMakeLists.txt
  windows/cmake/DownloadSDK.cmake
Labels: ci:schedule_run_ci

#2210 fix: catch exception of eventHandler when some unknown error code or …
  lib/src/binding/agora_base_event_impl.dart
  lib/src/binding/agora_h265_transcoder_event_impl.dart
  lib/src/binding/agora_media_base_event_impl.dart
  lib/src/binding/agora_media_player_event_impl.dart
  lib/src/binding/agora_media_player_source_event_impl.dart
  lib/src/binding/agora_music_content_center_event_impl.dart
  lib/src/binding/agora_rtc_engine_event_impl.dart
  pubspec.yaml
  test_shard/fake_test_app/integration_test/testcases/rtcengine_rtcengineeventhandler_testcases.dart
  tool/terra/renderers/event_handlers_impl_renderer.ts
Labels: ci:ready_release_special
