Repository AgoraIO-Extensions/Agora-Flutter-SDK, pull requests merged in 2025-06, with the labels that each got.

#2331 chore: upgrade sdk to 4.2.6.163
  lib/src/agora_rtc_engine.dart
  lib/src/agora_rtc_engine.g.dart
  lib/src/impl/agora_rtc_engine_impl.dart
  pubspec.yaml
  windows/CMakeLists.txt
Labels: version:special, ci:ready_release_special

#2333 feat: upgrade sdk to 4.2.6.163
  pubspec.yaml
  windows/CMakeLists.txt
Labels: ci:schedule_build_example, ci:building_example, ci:skip

#2327 Add Swift Package Manager Support
  example/ios/.gitignore
  example/ios/Runner.xcodeproj/project.pbxproj
  example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  example/macos/.gitignore
  example/macos/Runner.xcodeproj/project.pbxproj
  example/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  example/macos/Runner/AppDelegate.swift
  example/macos/Runner/MainFlutterWindow.swift
  ios/.gitignore
  ios/Assets/.gitkeep
  ios/Classes/TextureRenderer.h
  ios/Classes/TextureRenderer.mm
  ios/Classes/VideoViewController.h
  ios/Classes/VideoViewController.mm
  ios/agora_rtc_engine.podspec
  ios/agora_rtc_engine/Package.resolved
  ios/agora_rtc_engine/Package.swift
  ios/agora_rtc_engine/Sources/agora_rtc_engine/AgoraRtcNgPlugin.m
  ios/agora_rtc_engine/Sources/agora_rtc_engine/AgoraSurfaceViewFactory.mm
  ios/agora_rtc_engine/Sources/agora_rtc_engine/TextureRenderer.mm
  ios/agora_rtc_engine/Sources/agora_rtc_engine/VideoViewController.mm
  ios/agora_rtc_engine/Sources/agora_rtc_engine/include/agora_rtc_engine/AgoraRtcNgPlugin.h
  ios/agora_rtc_engine/Sources/agora_rtc_engine/include/agora_rtc_engine/AgoraSurfaceViewFactory.h
  ios/agora_rtc_engine/Sources/agora_rtc_engine/include/agora_rtc_engine/TextureRenderer.h
  ios/agora_rtc_engine/Sources/agora_rtc_engine/include/agora_rtc_engine/VideoViewController.h
  macos/.gitignore
  macos/Classes/AgoraCVPixelBufferUtils.h
  macos/Classes/AgoraCVPixelBufferUtils.mm
  macos/Classes/TextureRenderer.h
  macos/Classes/TextureRenderer.mm
  macos/Classes/VideoViewController.h
  macos/Classes/VideoViewController.mm
  macos/agora_rtc_engine.podspec
  macos/agora_rtc_engine/Package.resolved
  macos/agora_rtc_engine/Package.swift
  macos/agora_rtc_engine/Sources/agora_rtc_engine/AgoraCVPixelBufferUtils.mm
  macos/agora_rtc_engine/Sources/agora_rtc_engine/AgoraRtcNgPlugin.mm
  macos/agora_rtc_engine/Sources/agora_rtc_engine/TextureRenderer.mm
  macos/agora_rtc_engine/Sources/agora_rtc_engine/VideoViewController.mm
  macos/agora_rtc_engine/Sources/agora_rtc_engine/include/agora_rtc_engine/AgoraCVPixelBufferUtils.h
  macos/agora_rtc_engine/Sources/agora_rtc_engine/include/agora_rtc_engine/AgoraRtcNgPlugin.h
  macos/agora_rtc_engine/Sources/agora_rtc_engine/include/agora_rtc_engine/TextureRenderer.h
  macos/agora_rtc_engine/Sources/agora_rtc_engine/include/agora_rtc_engine/VideoViewController.h
  macos/agora_rtc_engine/Sources/agora_rtc_engine_swift/File.swift
  shared/darwin/TextureRenderer.h
  shared/darwin/TextureRenderer.mm
  shared/darwin/VideoViewController.h
  shared/darwin/VideoViewController.mm
Labels: ci:schedule_run_ci

#2345 chore: upgrade sdk to 4.3.2.246
  android/build.gradle
  android/src/main/cpp/third_party/include/agora_rtc/IAgoraMediaPlayer.h
  android/src/main/cpp/third_party/include/agora_rtc/IAgoraMediaPlayerSource.h
  android/src/main/cpp/third_party/include/agora_rtc/IAgoraRtcEngine.h
  example/lib/examples/advanced/send_metadata/send_metadata.dart
  ios/agora_rtc_engine.podspec
  lib/src/agora_media_player.dart
  lib/src/agora_media_player_source.dart
  lib/src/agora_rtc_engine.dart
  lib/src/agora_rtc_engine.g.dart
  lib/src/binding/agora_media_player_impl.dart
  lib/src/binding/agora_media_player_source_event_impl.dart
  lib/src/binding/call_api_event_handler_buffer_ext.dart
  lib/src/binding/event_handler_param_json.dart
  lib/src/binding/event_handler_param_json.g.dart
  lib/src/impl/agora_rtc_engine_impl.dart
  lib/src/impl/media_player_controller_impl.dart
  pubspec.yaml
  test_shard/iris_tester/cxx/src/fake_gen/fake_imediaplayer_internal.hpp
  test_shard/iris_tester/cxx/src/fake_gen/fake_imusicplayer_internal.hpp
Labels: ci:ready_release_special

#2326 chore: upgrade sdk to 4.2.6.163-build.3
  .github/workflows/build.yml
  .gitignore
  README.md
  android/build.gradle
  android/consumer-rules.pro
  example/android/app/build.gradle
  example/android/build.gradle
  example/android/gradle/wrapper/gradle-wrapper.properties
  example/web/index.html
  ios/agora_rtc_engine.podspec
  macos/agora_rtc_engine.podspec
  pubspec.yaml
  scripts/iris_web_version.js
  test_shard/fake_test_app/android/app/build.gradle
  test_shard/integration_test_app/android/app/build.gradle
  test_shard/integration_test_app/android/build.gradle
  test_shard/rendering_test/android/app/build.gradle
  test_shard/rendering_test/android/build.gradle
  windows/CMakeLists.txt
Labels: version:special, ci:schedule_run_ci

#2354 chore: upgrade sdk to 4.2.6.163-build.4
  pubspec.yaml
  windows/CMakeLists.txt
Labels: ci:skip
